version: '3.1'
services:
  nest:
    build: .
    container_name: raha_quiz_nest
    depends_on:
      - mariadb
    ports:
      - 3000:3000

  mariadb:
    image: mariadb:latest
    container_name: raha_quiz_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=raha
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./mariadb/data:/var/lib/mysql
